version: "2"

linters:
  default: none
  enable:
    - errcheck
    - gosec
    - govet
    - staticcheck
    - unused
    - gocyclo
  settings:
    gocyclo:
      min-complexity: 20
    errcheck:
      exclude-functions:
        - (*os.File).Close
        - (*io.PipeWriter).Close
        - (*io.PipeReader).Close
        - (io.Closer).Close
        - (*net/http.Response).Body.Close
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - (*github.com/spf13/pflag.FlagSet).MarkHidden
        - (*os/exec.Cmd).Run
    gosec:
      excludes:
        - G101
        - G104
        - G204
        - G301
        - G302
        - G304
        - G306
    staticcheck:
      checks:
        - "all"
        - "-QF*"
        - "-ST1000"
        - "-ST1003"

run:
  timeout: 5m
  tests: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
